name: Lint Go Code

on:
    push:
      branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
        with:
            stable: 'false'
            go-version: 1.19

    - name: Lint 
        run: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh 
            | sh -s -- -b $(go env GOPATH)/bin v1.26.0

            golangci-lint run  